baseURL = 'https://teilomillet.github.io/'
languageCode = 'en-us'
title = "teilomillet"
theme = 'hugo-dead-simple'

[params]
author = "Teïlo Millet"
description = "Meta-curious layman"

# Social links
github = "teilomillet"
twitter = "teilomillet"
linkedin = "teilomillet"
email = "teilomillet@gmail.com"

[menu]
[[menu.main]]
name = "Posts"
url = "/"
weight = 1
